twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['bootstrap_5_layout.html.twig']
    exception_controller: null
    globals:
        domain: '%domain%'

when@test:
    twig:
        strict_variables: true
